baseurl: https://sprightly-crisp-e68084.netlify.app  # Update 
title: National Mental Health Systems Modelling Network
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
#disqusShortname: # Option for future.
googleAnalytics: '' # Option
summaryLength: 70
paginate: 10
pluralizelisttitles: no
menu:
  main:
    - identifier: menu.home # Resources (publications / talks) / Models / Code & Data / Blogs
      name: Home
      url: /
      weight: 1
    - identifier: menu.aboutus
      name: About us
      url: /img/banners/hadija-saidi-unsplash.jpg #Photo by <a href="https://unsplash.com/@hadijasaidi?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Hadija Saidi</a> on <a href="https://unsplash.com/s/photos/question?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
      weight: 2
    - identifier: section.whyandwho
      name: Motivation and expertise
      parent: menu.aboutus
      post: 1
      url: ''
      weight: 1
    - name: 'Our purpose'
      parent: section.whyandwho
      url: /purpose
      weight: 1
    - name: 'Our members'
      parent: section.whyandwho
      url: /members
      weight: 2
    - identifier: section.learnmore
      name: Learn more
      parent: menu.aboutus
      post: 2
      url: ''
      weight: 1
    - name: 'Support our work'
      parent: section.learnmore
      url: /supportus
      weight: 1
    - name: Contact us # Note need for Google API Key and Formspree free plan. Will also need to update email paramter on contact page.
      parent: section.learnmore
      url: /contact/
      weight: 2
    # - identifier: contact # Note need for Google API Key and Formspree free plan. Will also need to update email paramter on contact page.
    #   name: Contact
    #   url: /contact/
    #   weight: 7
    - identifier: menu.ourwork
      name: Our work
      url: /img/banners/rohan-makhecha-unsplash.jpg  #Photo by <a href="https://unsplash.com/@rohanmakhecha?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Rohan Makhecha</a> on <a href="https://unsplash.com/s/photos/insight?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
      weight: 3
    - identifier: section.publications
      name: Publications
      parent: menu.ourwork
      post: 1
      url: /blog/our-work/publications/ #Not used
      weight: 1
    - name: Modelling methods
      parent: section.publications
      url: /categories/publications-modelling-methods/
      weight: 1
    - name: Mental health policy
      parent: section.publications
      url: /categories/publications-mental-health-policy/
      weight: 2
    - identifier: section.decisionaids
      name: Decision Aids
      parent: menu.ourwork
      post: 2
      url: /blog/our-work/decision-aids/ #Not used
      weight: 2
    - name: Publicly available
      parent: section.decisionaids
      url: /blog/our-work/decision-aids/publicly-available/
      weight: 1
    - name: Restricted use
      parent: section.decisionaids
      url: /blog/our-work/decision-aids/restricted-access/
      weight: 2
    - identifier: menu.resources
      name: Resources
      url: /img/banners/marek-levak-unsplash.jpg #Photo by <a href="https://unsplash.com/@designmesk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Marek Levák</a> on <a href="https://unsplash.com/s/photos/tablet?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
      weight: 4
    - identifier: section.planners
      name: Resources for Planners
      parent: menu.resources
      post: 1
      url: ''
      weight: 1
    - name: Primers
      parent: section.planners
      url: /blog/resources/planner-resources/primers/
      weight: 1
    - name: Talks
      parent: section.planners
      url: /blog/resources/planner-resources/talks/
      weight: 2    
    - identifier: section.modellers
      name: Resources for Modellers
      parent: menu.resources
      post: 2
      url: ''
      weight: 3
    # - name: Guidance
    #   parent: section.modellers
    #   url: ''
    #   weight: 1
    - name: Open code and data
      parent: section.modellers
      url: /blog/resources/modeller-resources/open-code-and-data
      weight: 2
    # - name: Peer Network
    #   parent: section.modellers
    #   url: ''
    #   weight: 3
    - name: Tutorials
      parent: section.modellers
      url: /blog/resources/modeller-resources/tutorials/
      weight: 4
    # - name: Workshops
    #   parent: section.modellers
    #   url: ''
    #   weight: 5
    - identifier: menu.blog
      name: News and events
      url: /blog/news-and-events/
      weight: 5
  topbar:
    - name: Phone # We can remove
      pre: <i class='fas fa-2x fa-phone'></i>
      url: tel:+61 7 3271 8660 # Update if using
      weight: 1
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/mentalhealthmodels/
      weight: 2
    # - name: Facebook
    #   pre: <i class='fab fa-2x fa-facebook'></i>
    #   url: http://facebook.com
    #   weight: 3
    # - name: Twitter
    #   pre: <i class='fab fa-2x fa-twitter'></i>
    #   url: http://twitter.com
    #   weight: 4
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:info@qcmhr.uq.edu.au # Need to update
      weight: 5
params:
  about_us: <p>We are a network of academics, service planners and policy professionals who build and use models of mental health systems. We collaborate to improve the quality, usefulness and impact of these models.</p>
  address: "<p class=\"text-uppercase\"><strong>National Mental Health Systems Modelling Network.</strong>\n        <br>Queensland Centre for Mental Health Research\n        <br>Level 3, Dawson House\n        <br>The Park Centre for Mental Health Treatment,
Research and Education\n        <br>Wacol\n <br>QLD 4076\n
    \       <br>\n        <strong>Australia</strong>\n      </p>\n      "
  author: National Mental Health Systems Modelling Network
  carouselCustomers:
    auto_play: no
    items: 6
    pagination_speed: 1000
    slide_speed: 2000
  carouselHomepage:
    auto_play: yes
    enable: yes
    pagination_speed: 1000
    slide_speed: 2000
  carouselTestimonials:
    auto_play: no
    items: 4
    pagination_speed: 1000
    slide_speed: 2000
  clients:
    enable: no
    subtitle: ''
    title: Network Members
  contact_form_ajax: no
  contact_url: /contact/
  copyright: Copyright (c) 2022 - 2022, National Mental Health Systems Modelling Network; all rights reserved.
  date_format: January 2, 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: Supporting mental health reform through better decision models
  defaultKeywords:
    - mental health
    - systems modelling
    - decision models
    - simulation
  disabled_logo: yes # Can change when we have a logo
  dropdown_mouse_over: no # Better on?
  enableGoogleMaps: no # May decide to change this
  enableRecaptchaInContactForm: no
  #facebook_site: ''
  features:
    cols: 3
    enable: yes
  footer:
    recent_posts:
      enable: yes
  #formspree_action: https://formspree.io/sample/of/endpoint ### We need to set up an acount and update this.
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY ## Need to update this
  googleRecaptchaKey: site_key_for_google_recaptcha ## And probably this too
  latitude: '-27.49873516764946' #-, 
  logo: img/logo.png # Need to update when we have a logo
  logo_small: img/logo-small.png # Need to update when we have a logo
  logo_text: National Mental Health Systems Modelling Network
  longitude: '153.0118860343866'
  mainSections: blog
  recent_posts:
    enable: yes
    hide_summary: no
    subtitle: Some recently added resources about mental health modelling.
    title: Latest news and resources
  see_more:
    enable: yes
    icon: far fa-file-alt
    link_text: Learn more
    link_url: '/blog/resources/modeller-resources/open-code-and-data/'
    subtitle: We facilitate the sharing of model code and data through open access repositories.
    title: Open code and data
  style: marsala
  testimonials:
    enable: no
    subtitle: We are a network of modellers and service planners who work together to improve Australian population mental health.
    title: Why we work together
  topbar:
    enable: no # Could switch on
    text: "<p class=\"hidden-sm hidden-xs\">Contact us on +61 7 3271 8660 or info@qcmhr.uq.edu.au.</p>\n
      \     <p class=\"hidden-md hidden-lg\"><a href=\"tel:+61 7 3271 8660\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\n      <a href=\"mailto:info@qcmhr.uq.edu.au\"
      data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p>\n
      \     "
  #twitter_site: GoHugoIO # Can add if we have a Twitter Account
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
taxonomies:
  author: authors
  category: categories
  tag: tags
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
pygmentsUseClasses: true 
#pygmentsStyle: "native"
#pygmentsCodefences: true
ignoreFiles:
    - \.Rmd$
    - _files$
    - _cache$
    - \.knit\.md$
    - \.utf8\.md$